config/routes.rb
TorrentTracker::Application.routes.draw do
  resources :torrents do
    member do
      get :download
    end
  end
  resources :feeds
  resources :trackings

end

app/models/feed.rb
require 'rss/1.0'
require 'rss/2.0'

class Feed < ActiveRecord::Base
  has_many :torrents

  validates :url, :name, :presence => true

  class << self
    def save_all_new_torrent_data
      Feed.all.each do |feed|
        feed.save_new_torrent_data
      end
    end

    def download_all_torrent_data
      items = []
      Feed.all.each do |feed|
        items << feed.download_torrent_data
      end
      items.flatten
    end
  end

  def save_new_torrent_data
    download_torrent_data.each do |rss_torrent|
      torrent = Torrent.find_or_initialize_by_link(rss_torrent.link)
      self.torrents << torrent if torrent.new_record?
      save_rss_data_to_torrent(torrent, rss_torrent)
    end
  end

  def download_torrent_data
    body = RestClient.get(url)
    rss = RSS::Parser.parse(body, false)
    rss.items
  end

  private

  def save_rss_data_to_torrent(torrent, rss_torrent)
    torrent.title = rss_torrent.title
    torrent.published = rss_torrent.pubDate.to_datetime
    torrent.category = rss_torrent.category.content
    torrent.description = rss_torrent.description
    torrent.save
  end
end

app/models/torrent.rb
require 'net/http'

class Torrent < ActiveRecord::Base
  belongs_to :tracking
  belongs_to :feed

  delegate :destination, :to => :tracking
  delegate :name, :to => :feed, :prefix => true, :allow_nil => true

  validates :title, :link, :published, :presence => true

  before_validation :extract_filename_from_link

  class << self
    def unmatched
      Torrent.where(:tracking_id => nil)
    end
    def categories
      Torrent.group("category").collect(&:category)
    end

    def match(*trackings)
      matches = []
      torrents = Torrent.unmatched
      trackings.flatten.each do |tracking|
        torrents.each do |torrent|
          if is_matching?(tracking, torrent)
            matches << torrent
            tracking.torrents << torrent
          end
        end
      end
      matches
    end

    def is_matching?(tracking, torrent)
      torrent.title.match(tracking.title) &&
      (tracking.categories.nil? || tracking.categories.include?(torrent.category))
    end

    def download_folder
      File.expand_path(TorrentTracker::Application.settings[:torrent_download_folder])
    end
  end

  def download
    create_download_folder
    save_torrent_file
    downloaded!
  end

  def copied!
    update_attribute :copied, true
  end

  def downloaded!
    update_attribute :downloaded, true
  end

  def is_category?(category)
    self.category == category
  end

  private

  def create_download_folder
    FileUtils.mkdir_p Torrent.download_folder
  end

  def save_torrent_file
    uri = URI.parse(link)
    Net::HTTP.start(uri.host, uri.port) do |http|
      write_response_to_file http.get(uri.path)
    end
  end

  def extract_filename_from_link
    self.filename = File.basename(link) unless link.nil?
  end

  def write_response_to_file(response)
    open("#{Torrent.download_folder}/#{title}.torrent", "wb") do |file|
      file.write response.body
    end
  end

end

app/models/tracking.rb
class Tracking < ActiveRecord::Base
  has_many :torrents

  validates :title, :destination, :presence => true

  serialize :categories

  def self.find_matching_torrents
    matches = Torrent.match Tracking.all
  end

  def has_category?(category)
    categories.present? && categories.include?(category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :get_feed, :only => [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(params[:feed])

    if @feed.save
      redirect_to feeds_path, :notice => 'Feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feed.update_attributes(params[:feed])
      redirect_to feeds_path, :notice => 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feed.destroy
    redirect_to feeds_url
  end

  private

  def get_feed
    @feed = Feed.find(params[:id])
  end
end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController
  def index
    @torrents = Torrent.order("published DESC")
  end

  def download
    Torrent.find(params[:id]).download
    redirect_to torrents_path, :notice => 'Torrent was successfully downloaded.'
  end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_filter :get_tracking, :only => [:show, :edit, :update, :destroy]

  def index
    @trackings = Tracking.all
  end

  def show
  end

  def new
    @tracking = Tracking.new
  end

  def edit
  end

  def create
    @tracking = Tracking.new(params[:tracking])
    if @tracking.save
      redirect_to trackings_path, :notice => 'Tracking was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tracking.update_attributes(params[:tracking])
      redirect_to @tracking, :notice => 'Tracking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tracking.destroy
    redirect_to trackings_url
  end

  private

  def get_tracking
    @tracking = Tracking.find(params[:id])
  end
end

app/views/feeds/_form.html.haml
= form_for feed do |f|
  -if feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - feed.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :name, "Name"
    = f.text_field :name
  %p
    = f.label :url, "URL"
    = f.text_field :url
  .actions
    = f.submit 'Add'

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form', :feed => @feed

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
%h1 Listing feeds
= link_to_function "Toggle panel", "panel.toggle()"

#panel
#entries_container
  %table
    %tr
      %th
      %th
      %th
      %th
      %th

    - @feeds.each do |feed|
      %tr
        %td= feed.name
        %td= link_to 'Edit', edit_feed_path(feed)
        %td= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete

  %br

= link_to 'New Feed', new_feed_path
= link_to 'Trackings', trackings_path
= link_to 'Torrents', torrents_path

app/views/feeds/new.html.haml
%h1 New feed

= render 'form', :feed => @feed

= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_feed_path(@feed)
\|
= link_to 'Back', feeds_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title TorrentTracker
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %p#notice= notice
    = yield

app/views/torrents/index.html.haml
%h1 Listing torrents

%table
  %tr
    %th Name
    %th Category
    %th Published
    %th Feed
    %th
    %th
    %th
  - @torrents.each do |torrent|
    %tr
      %td= torrent.title
      %td= torrent.category
      %td= torrent.published.to_s(:short)
      %td= torrent.feed_name
      %td= (torrent.copied?) ? "Copied" : "Not copied"
      %td= (torrent.downloaded?) ? "Downloaded" : "Not downloaded"
      %td= link_to "Download", download_torrent_path(torrent)
    - if torrent.description?
      %tr
        %td{:colspan => 6}= torrent.description.html_safe

= link_to 'Feeds', feeds_path
= link_to 'Trackings', trackings_path

app/views/trackings/_form.html.haml
%h1 Track a torrent
= form_for tracking do |f|
  -if tracking.errors.any?
    #error_explanation
      %h2= "#{pluralize(tracking.errors.count, "error")} prohibited this tracking from being saved:"
      %ul
        - tracking.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title, "Torrent title"
    = f.text_field :title
  %p
    = f.label :destination, "Destination"
    = f.text_field :destination
  %p
    - Torrent.categories.each do |category|
      = check_box_tag "tracking[categories][]", category, tracking.has_category?(category), :id => category.parameterize
      = label_tag category.parameterize, category
  .actions
    = f.submit 'Add'

app/views/trackings/edit.html.haml
%h1 Editing tracking

= render 'form', :tracking => @tracking

= link_to 'Show', @tracking
\|
= link_to 'Back', trackings_path

app/views/trackings/index.html.haml
%h1 Listing trackings

%table
  %tr
    %th Title
    %th Categoris
    %th
    %th
    %th

  - @trackings.each do |tracking|
    %tr
      %td= tracking.title
      %td= (tracking.categories) ? tracking.categories.to_sentence : "No category"
      %td= link_to 'Show', tracking
      %td= link_to 'Edit', edit_tracking_path(tracking)
      %td= link_to 'Destroy', tracking, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Tracking', new_tracking_path
= link_to 'Feeds', feeds_path
= link_to 'Torrents', torrents_path

app/views/trackings/new.html.haml
%h1 New tracking

= render 'form', :tracking => @tracking

= link_to 'Back', trackings_path

app/views/trackings/show.html.haml
= @tracking.title

= link_to 'Edit', edit_tracking_path(@tracking)
\|
= link_to 'Back', trackings_path